# Site settings
title: GSNP Tutorial 2023
tag_text: GSNP Tutorial 2023
description: Computational modelling and information theory tutorial at the 2023 APS March meeting in Las Vegas, NV

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
